global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: "pipeline-latency"
    metrics_path: "/metrics"
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:8009"]
  - job_name: 'kubernetes-pods'
    scrape_interval: 1s
    kubernetes_sd_configs:
      - kubeconfig_file: /etc/prometheus/kube.config
        role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: mehran
