apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
 name: pelastic-podmonitor
 namespace: observability
 labels:
  release: kube-prom-stack  # https://github.com/prometheus-operator/prometheus-operator/issues/3636
spec:
 namespaceSelector:
  any: true
 podMetricsEndpoints:
 - interval: 1s
   path: /metrics
 selector:
   matchLabels:
     project: pelastic